workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - example_bipartition
#      - deploy:
#          requires:
#            - build
#          filters:
#            branches:
#              only: master



version: 2
jobs:
  build:
    docker:
      - image: edyirdaw/snet_network_analytics:v1
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: |
            cd services
            python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. network_analytics.proto
            python3 test_bipartite_graphs.py
            python3 test_snet_grpc_wrapper.py